version: '3.9'

services:
  web:
    build: .
    command: gunicorn core.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
    - 8000:8000
  db:
    image: postgres:11
    volumes:
      - develops_postgres_data:/var/lib/postgresql/data/
    container_name: develops_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=develops
      - POSTGRES_DB=develops
    
volumes:
    develops_postgres_data: