version: '3.9'

services:
  web:
    build: .
    command: bash -c "python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
    - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:11
    volumes:
      - develops_postgres_data:/var/lib/postgresql/data/
    container_name: develops_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=develops
      - POSTGRES_DB=develops
    
volumes:
    develops_postgres_data: