# Generated by Django 4.0.3 on 2022-03-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_no_of_votes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="author_name",
        ),
    ]
